name:
  simulink_pipeline

on:
  workflow_dispatch:

permissions:
  checks:
    write

  contents:
    read


env:
  PATH_TO_MATLAB:
    C:\Program Files\MATLAB\R2025b\bin\win64\MATLAB.exe


jobs:
  Restore_Cache:
    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Restore Cache

        uses:
          actions/cache@v4

        with:
          key:
            padv_artifacts-${{ github.run_id }}-${{ github.run_attempt }}

          restore-keys:
            padv_artifacts-cache

          path:
            |
            03_Code
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/metrics
            04_Results/AHRS_Voter/model_comparison
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/metrics
            04_Results/Actuator_Control/model_comparison
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/metrics
            04_Results/Flight_Control/model_comparison
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/metrics
            04_Results/InnerLoop_Control/model_comparison
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/metrics
            04_Results/OuterLoop_Control/model_comparison
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results/findAcrossModelClones
            04_Results/test_results/findLibraryClones
            derived/artifacts.dmr


      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            03_Code
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/metrics
            04_Results/AHRS_Voter/model_comparison
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/metrics
            04_Results/Actuator_Control/model_comparison
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/metrics
            04_Results/Flight_Control/model_comparison
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/metrics
            04_Results/InnerLoop_Control/model_comparison
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/metrics
            04_Results/OuterLoop_Control/model_comparison
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results/findAcrossModelClones
            04_Results/test_results/findLibraryClones

          retention-days:
            30




  Runprocess:
    if:
      ${{ !cancelled() }}

    needs:
      Restore_Cache

    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts


      - name:
          Setup MATLAB

        run:
          echo "$PATH_TO_MATLAB" >> $GITHUB_PATH

      - name:
          Launch MATLAB

        run:
          >
          matlab 
          -nodesktop 
          -logfile output.log 
          -batch "openProject(pwd);runprocess(Process = 'CIPipeline', Force = false, ExitInBatchMode = true, RerunFailedTasks = false, RerunErroredTasks = false, GenerateJUnitForProcess = false);" 

      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Runprocess_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            03_Code
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/metrics
            04_Results/AHRS_Voter/model_comparison
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/metrics
            04_Results/Actuator_Control/model_comparison
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/metrics
            04_Results/Flight_Control/model_comparison
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/metrics
            04_Results/InnerLoop_Control/model_comparison
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/metrics
            04_Results/OuterLoop_Control/model_comparison
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results/findAcrossModelClones
            04_Results/test_results/findLibraryClones

          retention-days:
            30




  Generate_PADV_Report:
    if:
      ${{ !cancelled() }}

    needs:
      Runprocess

    runs-on:
      self-hosted

    steps:
      - name:
          Checkout Repository

        uses:
          actions/checkout@v4

      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts


      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Runprocess_padv_artifacts


      - name:
          Setup MATLAB

        run:
          echo "$PATH_TO_MATLAB" >> $GITHUB_PATH

      - name:
          Generate PADV Report

        run:
          >
          matlab 
          -nodesktop 
          -logfile output.log 
          -batch "openProject(pwd);
          rptObj=padv.ProcessAdvisorReportGenerator(Process = 'CIPipeline', Format='pdf', OutputPath=fullfile(currentProject().RootFolder,'ProcessAdvisorReport'));
          rptObj.generateReport();" 

      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Generate_PADV_Report_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            ProcessAdvisorReport.pdf

          retention-days:
            30




  Collect_Artifacts:
    if:
      ${{ !cancelled() }}

    needs:
      Generate_PADV_Report

    runs-on:
      self-hosted

    steps:
      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Restore_Cache_padv_artifacts


      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Runprocess_padv_artifacts


      - name:
          Download Artifacts

        uses:
          actions/download-artifact@v4

        with:
          name:
            Generate_PADV_Report_padv_artifacts


      - name:
          Upload Artifacts

        if:
          ${{ !cancelled() }}

        uses:
          actions/upload-artifact@v4

        with:
          name:
            Collect_Artifacts_padv_artifacts

          path:
            |
            derived/artifacts.dmr
            03_Code
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/metrics
            04_Results/AHRS_Voter/model_comparison
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/metrics
            04_Results/Actuator_Control/model_comparison
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/metrics
            04_Results/Flight_Control/model_comparison
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/metrics
            04_Results/InnerLoop_Control/model_comparison
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/metrics
            04_Results/OuterLoop_Control/model_comparison
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results/findAcrossModelClones
            04_Results/test_results/findLibraryClones

          retention-days:
            30


      - name:
          Save Cache

        uses:
          actions/cache@v4

        with:
          key:
            padv_artifacts-cache-${{ github.sha }}

          path:
            |
            03_Code
            04_Results/AHRS_Voter/code_inspection
            04_Results/AHRS_Voter/design_error_detections
            04_Results/AHRS_Voter/metrics
            04_Results/AHRS_Voter/model_comparison
            04_Results/AHRS_Voter/model_standards_results
            04_Results/AHRS_Voter/system_design_description
            04_Results/AHRS_Voter/webview
            04_Results/Actuator_Control/code_inspection
            04_Results/Actuator_Control/design_error_detections
            04_Results/Actuator_Control/metrics
            04_Results/Actuator_Control/model_comparison
            04_Results/Actuator_Control/model_standards_results
            04_Results/Actuator_Control/system_design_description
            04_Results/Actuator_Control/webview
            04_Results/Flight_Control/code_inspection
            04_Results/Flight_Control/design_error_detections
            04_Results/Flight_Control/metrics
            04_Results/Flight_Control/model_comparison
            04_Results/Flight_Control/model_standards_results
            04_Results/Flight_Control/system_design_description
            04_Results/Flight_Control/webview
            04_Results/InnerLoop_Control/code_inspection
            04_Results/InnerLoop_Control/design_error_detections
            04_Results/InnerLoop_Control/metrics
            04_Results/InnerLoop_Control/model_comparison
            04_Results/InnerLoop_Control/model_standards_results
            04_Results/InnerLoop_Control/system_design_description
            04_Results/InnerLoop_Control/webview
            04_Results/OuterLoop_Control/code_inspection
            04_Results/OuterLoop_Control/design_error_detections
            04_Results/OuterLoop_Control/metrics
            04_Results/OuterLoop_Control/model_comparison
            04_Results/OuterLoop_Control/model_standards_results
            04_Results/OuterLoop_Control/system_design_description
            04_Results/OuterLoop_Control/webview
            04_Results/test_results/findAcrossModelClones
            04_Results/test_results/findLibraryClones
            derived/artifacts.dmr





